# Site settings
# in the templates available like {{ site.myvariable }}.
title: Từ thiện THIỆN NGUYỆN
email: your-email@domain.com
brand: Từ thiện THIỆN NGUYỆN
headline: Quê Hương Là Chùm Khế Ngọt, Cho con trèo hái mỗi ngày!
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2019 KERI Company http//keri.vn, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: Tam David
phone: +1-800-555-2016

# Tracking
googleAnalitycsID: UA-83933844-1

