# Site settings
# in the templates available like {{ site.myvariable }}.
title: Trang web tu thien
email: your-email@domain.com
brand: Web tu thien cua Viet Kieu My
headline: Que huong la chum khe ngot
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: Tam David
phone: +1-800-555-2016

# Tracking
googleAnalitycsID: UA-83933844-1

